import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "./Head";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NightFall Webworks",
  description: "Generated by create next app",
  icons: {
    icon: "./nightfallwebworks.avif",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <Head />        
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
